import { ViewerParams, ViewerAnimate, ViewerCamera, ViewerAmbient, ViewerEvent, ViewerModel, ViewerFog, ViewerControl, ViewerSky, ViewerEnvironment, ViewerSource, ViewerParade, ViewerWater, ViewerSkyLight, ViewerDirectional, PointLightType, ViewerSpot, ViewerRectArea, ViewerRoam } from "../types/types";
export declare class Params {
    clock: THREE.Clock;
    animate: ViewerAnimate;
    gAmGroup: THREE.Group[];
    gRayGroup: THREE.Group[];
    gScenes: THREE.Scene[];
    gStatus: boolean[];
    scene: THREE.Scene;
    model: ViewerModel;
    sceneidx: number;
    cameraClass: ViewerCamera;
    activeCamera: THREE.Camera;
    renderer: THREE.WebGLRenderer;
    controls: ViewerControl;
    ambient: ViewerAmbient;
    hemisphereLight: ViewerSkyLight;
    directional: ViewerDirectional;
    pointGroup: PointLightType[];
    spotLight: ViewerSpot;
    rectAreaLight: ViewerRectArea;
    sky: ViewerSky;
    environment: ViewerEnvironment;
    event: ViewerEvent;
    souce: ViewerSource;
    parade: ViewerParade;
    spriteGroup: THREE.Object3D[];
    fog: ViewerFog;
    water: ViewerWater;
    roam: ViewerRoam;
    options: ViewerParams;
    constructor(options: ViewerParams);
}
